# /// script
# requires-python = ">=3.10"
# dependencies = ["pypng==0.20220715.0", "pillow==12.3.0"]
# ///
"""Build tests/pngsuite/reference.tsv from decoders paeth has nothing to do with.

    uv run tools/gen_reference.py

For every PngSuite file this records either `reject` or the SHA-256 of
its pixels as RGBA8 and as RGBA16 (big-endian), as decoded by pypng, a
pure-Python decoder written independently of paeth. The conformance test
(tests/pngsuite.rs) then checks paeth against these hashes.

pypng is checked in turn against Pillow, a third decoder with its own C
implementation. Pillow cannot represent 16-bit samples, keeping only the
high byte, so the comparison is Pillow's RGBA8 against pypng's RGBA16
shifted right by 8. Every disagreement must be one listed in
KNOWN_PILLOW_BUGS, with the reason, or the script fails.

Rescaling follows the PNG spec (section 13.12): round(v * MAXOUT / MAXIN).
pypng's asDirect() would also shift samples down to the precision the
sBIT chunk declares, which is a presentation choice the spec leaves to
the application; that step is disabled here, because paeth, like libpng
by default, returns the stored samples.
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import png
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SUITE = ROOT / "tests" / "pngsuite"
OUT = SUITE / "reference.tsv"

KNOWN_PILLOW_BUGS = {
    "tbbn0g04.png": (
        "4-bit gray with tRNS gray=15. Pillow compares the key against the "
        "sample after scaling it to 8 bits (255), so no pixel matches and the "
        "transparent pixels come out opaque. The spec compares raw samples."
    ),
}


def pypng_rgba(path: Path, depth: int) -> tuple[int, int, list[int]]:
    reader = png.Reader(filename=str(path))
    reader.preamble()
    reader.sbit = None  # see the module docstring
    width, height, rows, _ = reader._as_rescale(reader.asRGBA, depth)
    return width, height, [v for row in rows for v in row]


def pillow_rgba8(path: Path) -> list[int]:
    with Image.open(path) as im:
        im.load()
        if im.mode.startswith("I;16"):
            # 16-bit gray: Pillow's RGBA conversion clips instead of
            # scaling, so take the high byte the way it does for RGB16,
            # and apply the tRNS key it reports.
            key = im.info.get("transparency")
            flat = getattr(im, "get_flattened_data", im.getdata)()
            gray: list[int] = [int(g) for g in flat]
            return [v >> 8 for g in gray for v in (g, g, g, 0 if g == key else 0xFFFF)]
        return list(im.convert("RGBA").tobytes())


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    files = sorted(SUITE.glob("*.png"))
    lines = [
        "# PngSuite reference, generated by tools/gen_reference.py. Do not edit.",
        f"# decoder: pypng {png.__version__}; cross-checked against Pillow {Image.__version__}",
        "# columns: file, verdict, width, height, sha256(RGBA8), sha256(RGBA16 big-endian)",
    ]
    valid = rejected = agree = 0
    disagreements: dict[str, int] = {}
    for path in files:
        name = path.name
        must_reject = name.startswith("x")  # PngSuite's naming convention
        try:
            width, height, rgba8 = pypng_rgba(path, 8)
            _, _, rgba16 = pypng_rgba(path, 16)
        except Exception as e:  # pypng raises several unrelated types
            if not must_reject:
                print(f"{name}: pypng rejected a valid file: {e}", file=sys.stderr)
                return 1
            lines.append(f"{name}\treject")
            rejected += 1
            continue
        if must_reject:
            print(f"{name}: pypng accepted a corrupt file", file=sys.stderr)
            return 1

        # Sanity: RGBA8 must be RGBA16 rounded, per the spec's formula.
        assert rgba8 == [(v * 255 + 32767) // 65535 for v in rgba16], name

        pillow = pillow_rgba8(path)
        high_bytes = [v >> 8 for v in rgba16]
        if pillow == high_bytes:
            agree += 1
        else:
            disagreements[name] = sum(a != b for a, b in zip(pillow, high_bytes))

        rgba16_be = b"".join(v.to_bytes(2, "big") for v in rgba16)
        lines.append(
            f"{name}\tok\t{width}\t{height}\t{sha256(bytes(rgba8))}\t{sha256(rgba16_be)}"
        )
        valid += 1

    unexpected = set(disagreements) ^ set(KNOWN_PILLOW_BUGS)
    if unexpected:
        print(f"unexpected pypng/Pillow disagreement: {sorted(unexpected)}", file=sys.stderr)
        return 1

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(files)} files: {valid} valid, {rejected} rejected by pypng")
    print(f"Pillow agrees with pypng on {agree} of {valid} valid files")
    for name, count in disagreements.items():
        print(f"  {name}: {count} channel values differ. {KNOWN_PILLOW_BUGS[name]}")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
